FROM shyouhei/ruby-and-selenium-and-chrome:base

RUN set -ex \
 && mkdir -p /var/lib/apt/lists/partial \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
     ruby=1:2.1.6+0nkmi2~xenial \
     ruby2.1=2.1.9-0nkmi1~xenial \
     libruby2.1=2.1.9-0nkmi1~xenial \
     ruby2.1-dev=2.1.9-0nkmi1~xenial \
 && apt-get autoremove \
 && apt-get clean \
 && rm -rf /var/cache/apt/archives /var/lib/apt/lists

RUN gem install bundler
