FROM alpine:3.11
MAINTAINER shyouhei@ruby-lang.org

RUN apk add --no-cache \
    autoconf \
    bison \
    gcc \
    gdbm-dev \
    glib-dev \
    gmp-dev \
    libc-dev \
    libffi-dev \
    libxml2-dev \
    libxslt-dev \
    linux-headers \
    make \
    ncurses-dev \
    openssl \
    openssl-dev \
    procps \
    readline-dev \
    ruby \
    yaml-dev \
    zlib-dev \
