version: "3.7"
services:
  apt-cacher-ng:
    build: .
    image: shyouhei/apt-cacher-ng
    container_name: apt-cacher-ng
    restart: unless-stopped
    ports:
      - target: "3142"
        published: "3142"
        protocol: "tcp"
        mode: "host"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    dns_search:
      - configure.ac
    volumes:
      - type: volume
        source: apt-cacher-ng
        target: /var/cache/apt-cacher-ng

volumes:
  apt-cacher-ng:
    name: apt-cacher-ng
    driver: local
    
