# This docker-compose.yml won't interface well with the pseudo tty.

version: "3.7"
services:
  dev-base:
    build: .
    image: shyouhei/dev-base

  dev-tmux:
    build:
      context: .
      dockerfile: tmux-Dockerfile
    image: shyouhei/dev-tmux
    depends_on: ["dev-base"]
    stdin_open: true
    tty: true
    privileged: false
    init: true
    environment:
      DISPLAY:
      TZ:
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        read_only: true
        source: /etc/timezone
        target: /etc/timezone
      - type: bind
        read_only: true
        source: /etc/localtime
        target: /etc/localtime
      - type: bind
        source: /home/shyouhei
        target: /home/shyouhei
    # https://stackoverflow.com/a/46676907
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
